# Generated by Django 4.2.30 on 2026-10-05 12:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('mentored', '0009_sitesettings'),
        ('school', '0009_course_whatsapp_group_url'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailTemplate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.SlugField(help_text='registration, purchase, course_access и т.д.', unique=True, verbose_name='Код шаблона')),
                ('name', models.CharField(max_length=255, verbose_name='Название')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема (по умолчанию)')),
                ('html_body', models.TextField(help_text='Поддерживает переменные: {{ nombre }}, {{ numero_pedido }} и т.д.', verbose_name='HTML-тело')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Шаблон письма',
                'verbose_name_plural': 'Шаблоны писем',
                'ordering': ['code'],
            },
        ),
        migrations.CreateModel(
            name='EmailLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('recipient_email', models.EmailField(max_length=254, verbose_name='Email получателя')),
                ('email_type', models.CharField(help_text='registration, purchase, course_access, consultation_request, consultation_confirmed, consultation_reminder, payment_failed, admin_new_purchase', max_length=50, verbose_name='Тип письма')),
                ('subject', models.CharField(max_length=255, verbose_name='Тема')),
                ('status', models.CharField(choices=[('pending', 'Ожидает отправки'), ('sent', 'Отправлено'), ('failed', 'Ошибка отправки')], default='pending', max_length=20, verbose_name='Статус')),
                ('error_message', models.TextField(blank=True, verbose_name='Текст ошибки')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('recipient_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('related_course', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='school.course', verbose_name='Курс')),
                ('related_order', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='mentored.order', verbose_name='Заказ')),
                ('related_product', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='email_logs', to='mentored.course', verbose_name='Товар (витрина)')),
            ],
            options={
                'verbose_name': 'Лог письма',
                'verbose_name_plural': 'Журнал писем',
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['email_type', 'status'], name='notificatio_email_t_9447d8_idx'), models.Index(fields=['recipient_email'], name='notificatio_recipie_25af1a_idx'), models.Index(fields=['-created_at'], name='notificatio_created_4c6dec_idx')],
            },
        ),
    ]
