# Generated by Django 4.2.30 on 2026-09-03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0002_forumthread_forumpost_directmessage'),
    ]

    operations = [
        migrations.AddField(
            model_name='submission',
            name='is_public',
            field=models.BooleanField(default=False, help_text='По умолчанию ответ видят только автор и преподаватели; ученик может открыть его для остальных студентов курса', verbose_name='Виден другим ученикам'),
        ),
        migrations.CreateModel(
            name='SubmissionComment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField(verbose_name='Текст комментария')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата')),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='submission_comments', to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
                ('submission', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comments', to='school.submission', verbose_name='Ответ на задание')),
            ],
            options={
                'verbose_name': 'Комментарий к ответу',
                'verbose_name_plural': 'Комментарии к ответам',
                'ordering': ['created_at'],
            },
        ),
    ]
