# Generated by Django 4.2.30 on 2026-09-03

from django.db import migrations, models
import mentored.utils


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0003_submission_is_public_submissioncomment'),
    ]

    operations = [
        migrations.AddField(
            model_name='lesson',
            name='video_file',
            field=models.FileField(blank=True, help_text='Загруженный на сервер файл (mp4 и т.п.) - если заполнен, плеер использует его вместо ссылки ниже; так поддерживается пересчёт позиции просмотра (последняя минута сохраняется автоматически)', null=True, upload_to=mentored.utils.get_upload_path, verbose_name='Видеофайл'),
        ),
        migrations.AlterField(
            model_name='lesson',
            name='video_url',
            field=models.URLField(blank=True, help_text='Vimeo/YouTube/облако - используется только если видеофайл выше не загружен', null=True, verbose_name='Ссылка на видео (запасной вариант)'),
        ),
    ]
