# Generated by Django 4.2.30 on 2026-09-07

from django.db import migrations, models
import mentored.utils


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0005_certificate'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='certificate_template',
            field=models.ImageField(blank=True, help_text='Если не загружен - используется общий шаблон по умолчанию. ВАЖНО: картинка должна быть того же размера и разметки, что и шаблон по умолчанию (1280x906, текстовая зона x=75..740) - имя студента/название курса/дата накладываются на фиксированные координаты, другой макет "поедет".', null=True, upload_to=mentored.utils.get_upload_path, verbose_name='Шаблон сертификата'),
        ),
    ]
