# Generated by Django 4.2.30 on 2026-09-08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0006_course_certificate_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='creator',
            field=models.ForeignKey(blank=True, help_text='Преподаватель, создавший курс из своего кабинета - этот курс автоматически виден ему в «Mis cursos»', limit_choices_to={'roles__codename': 'teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_courses', to=settings.AUTH_USER_MODEL, verbose_name='Создатель курса'),
        ),
    ]
