# Generated by Django 4.2.30 on 2026-09-09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0007_course_creator'),
    ]

    operations = [
        migrations.AddField(
            model_name='assignment',
            name='is_required',
            field=models.BooleanField(default=True, help_text='Пока не выключено - урок нельзя отметить пройденным, пока студент не отправит ответ на это задание. Если выключить - задание необязательное, урок можно завершить и без него.', verbose_name='Обязательное'),
        ),
    ]
