# Generated by Django 4.2.30 on 2026-10-08 09:57

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('school', '0009_course_whatsapp_group_url'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumpost',
            name='edited_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отредактировано'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='edited_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='edited_forum_posts', to=settings.AUTH_USER_MODEL, verbose_name='Кто отредактировал'),
        ),
        migrations.AddField(
            model_name='forumpost',
            name='is_hidden',
            field=models.BooleanField(default=False, help_text='Скрытые посты видят только модераторы (автор и остальные - нет)', verbose_name='Скрыто'),
        ),
    ]
