# Generated by Django 4.2.30 on 2026-10-08 13:33

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0010_forumpost_edited_at_forumpost_edited_by_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='forumthread',
            name='lesson',
            field=models.ForeignKey(blank=True, help_text='Если заполнено — тема относится к обсуждению урока', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='forum_threads', to='school.lesson', verbose_name='Урок'),
        ),
    ]
