# Generated by Django 4.2.30 on 2026-10-08 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0011_forumthread_lesson'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='access_duration_days',
            field=models.PositiveIntegerField(blank=True, help_text='Для режима "Duración". Например, 30 — доступ на 30 дней после покупки.', null=True, verbose_name='Duración de acceso (días)'),
        ),
        migrations.AddField(
            model_name='course',
            name='access_end',
            field=models.DateTimeField(blank=True, help_text='Для режима "Fechas fijas". После этой даты доступ пропадает.', null=True, verbose_name='Fin de acceso'),
        ),
        migrations.AddField(
            model_name='course',
            name='access_mode',
            field=models.CharField(choices=[('unlimited', 'Sin límite'), ('duration', 'Duración desde la compra (días)'), ('dates', 'Fechas fijas')], default='unlimited', help_text='Sin límite — курс доступен бессрочно. Duración — доступ открывается на N дней после покупки. Fechas fijas — доступ только в указанном окне дат.', max_length=20, verbose_name='Modo de acceso'),
        ),
        migrations.AddField(
            model_name='course',
            name='access_start',
            field=models.DateTimeField(blank=True, help_text='Для режима "Fechas fijas". До этой даты курс недоступен.', null=True, verbose_name='Inicio de acceso'),
        ),
        migrations.AddField(
            model_name='enrollment',
            name='access_expires_at',
            field=models.DateTimeField(blank=True, help_text='Считается автоматически при создании доступа, исходя из настроек курса. Может быть изменено вручную (продление).', null=True, verbose_name='Acceso vence en'),
        ),
    ]
