# Generated by Django 4.2.30 on 2026-10-08 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0012_course_access_duration_days_course_access_end_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='course',
            name='whatsapp_group_description',
            field=models.TextField(blank=True, help_text='Краткое описание группы или правила входа', verbose_name='Descripción / reglas de entrada'),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_group_is_visible',
            field=models.BooleanField(default=True, help_text='Если выключено — ученики не видят ссылку. Админ и преподаватель курса всегда видят её.', verbose_name='Mostrar a los alumnos'),
        ),
        migrations.AddField(
            model_name='course',
            name='whatsapp_group_name',
            field=models.CharField(blank=True, help_text='Например: MENTORED · Курс личностного роста', max_length=200, verbose_name='Nombre del grupo'),
        ),
    ]
