# Generated by Django 5.2.15 on 2026-07-19 18:34

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentored', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='book',
            name='acceso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='agenda',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Повестка дня'),
        ),
        migrations.AddField(
            model_name='consultation',
            name='format_consultation',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='course',
            name='acceso',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Доступ'),
        ),
        migrations.AddField(
            model_name='course',
            name='format_course',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='membership',
            name='format_membership',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Формат'),
        ),
        migrations.AddField(
            model_name='membership',
            name='permanencia',
            field=models.CharField(blank=True, max_length=50, null=True, verbose_name='Постоянство (для вывода в membership)'),
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_number', models.CharField(max_length=50, unique=True, verbose_name='Номер заказа')),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('processing', 'Processing'), ('completed', 'Completed'), ('cancelled', 'Cancelled'), ('refunded', 'Refunded')], default='pending', max_length=20, verbose_name='Статус')),
                ('subtotal', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Сумма без налогов')),
                ('tax', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Налоги')),
                ('shipping', models.DecimalField(decimal_places=2, default=0, max_digits=10, verbose_name='Доставка')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('is_digital', models.BooleanField(default=False, verbose_name='Цифровой заказ (без доставки)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('paid_at', models.DateTimeField(blank=True, null=True)),
                ('cart', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='order', to='mentored.cart', verbose_name='Корзина')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='orders', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
            ],
        ),
        migrations.CreateModel(
            name='OrderItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_type', models.CharField(blank=True, max_length=50, null=True, verbose_name='Тип товара (course, book, consultation, membership)')),
                ('product_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID товара')),
                ('product_name', models.CharField(max_length=255, verbose_name='Название товара')),
                ('product_sku', models.CharField(blank=True, max_length=100, null=True, verbose_name='Артикул')),
                ('product_price', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Цена товара')),
                ('quantity', models.PositiveIntegerField(default=1, verbose_name='Количество')),
                ('total', models.DecimalField(decimal_places=2, max_digits=10, verbose_name='Итоговая сумма')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата создания')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Дата обновления')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='mentored.order', verbose_name='Заказ')),
            ],
            options={
                'verbose_name': 'Элемент заказа',
                'verbose_name_plural': 'Элементы заказа',
                'ordering': ['id'],
            },
        ),
    ]
