# Generated by Django 4.2.30 on 2026-07-27 17:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentored', '0003_order_is_active_alter_order_cart_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContactMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Имя')),
                ('email', models.EmailField(max_length=254, verbose_name='Email')),
                ('motivo', models.CharField(choices=[('Consulta sobre cursos', 'Consulta sobre cursos'), ('Reservar una consulta 1:1', 'Reservar una consulta 1:1'), ('Mi pedido o pago', 'Mi pedido o pago'), ('Devoluciones', 'Devoluciones'), ('Colaboraciones', 'Colaboraciones'), ('Otro', 'Otro')], default='Otro', max_length=50, verbose_name='Тема обращения')),
                ('message', models.TextField(verbose_name='Сообщение')),
                ('is_read', models.BooleanField(default=False, verbose_name='Прочитано')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Дата отправки')),
            ],
            options={
                'verbose_name': 'Сообщение с формы контактов',
                'verbose_name_plural': 'Сообщения с формы контактов',
                'ordering': ['-created_at'],
            },
        ),
    ]
