# Generated by Django 4.2.30 on 2026-07-27 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentored', '0004_contactmessage'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(help_text='Имя и фамилия', max_length=150, unique=True, verbose_name='Имя пользователя'),
        ),
    ]
