# Generated by Django 4.2.30 on 2026-07-30 19:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentored', '0005_alter_user_username'),
    ]

    operations = [
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('codename', models.SlugField(help_text="Технический код на латинице, используется в проверках доступа (например 'student', 'teacher')", unique=True, verbose_name='Код роли')),
                ('name', models.CharField(max_length=100, verbose_name='Название')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
            ],
            options={
                'verbose_name': 'Роль',
                'verbose_name_plural': 'Роли',
                'ordering': ['name'],
            },
        ),
        migrations.AddField(
            model_name='user',
            name='roles',
            field=models.ManyToManyField(blank=True, help_text='Студент, преподаватель и т.д. Можно совмещать несколько ролей.', related_name='users', to='mentored.role', verbose_name='Роли'),
        ),
    ]
