# Generated by Django 4.2.30 on 2026-08-03 19:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mentored', '0007_seed_roles'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_dev',
            field=models.BooleanField(default=False, help_text='Персональный feature-flag: пользователь с этой галочкой видит на боевом сервере ещё не выпущенные разделы (школа/кабинеты). Для обычных пользователей эти разделы закрыты и на фронте, и в API.', verbose_name='Разработчик (доступ к закрытым разделам)'),
        ),
    ]
