# Generated by Django 4.2.30 on 2026-09-07

from django.db import migrations, models


def seed_site_settings(apps, schema_editor):
    """ Предзаполняем реальными данными, которые уже были жёстко зашиты во фронте. """
    SiteSettings = apps.get_model('mentored', 'SiteSettings')
    SiteSettings.objects.get_or_create(pk=1, defaults={
        'contact_email': 'info@mentoredgroup.com',
        'whatsapp_number': '51940304595',
        'instagram_url': 'https://www.instagram.com/irina.karbonova?utm_source=qr',
        'facebook_url': 'https://www.facebook.com/share/18wT3LwP2q/?mibextid=wwXIfr',
        'youtube_url': 'https://www.youtube.com/@IrinaArbonova',
        'linkedin_url': 'https://www.linkedin.com/in/irina-karbonova-3a4763101?utm_source=share_via&utm_content=profile&utm_medium=member_ios',
    })


class Migration(migrations.Migration):

    dependencies = [
        ('mentored', '0008_user_is_dev'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteSettings',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contact_email', models.EmailField(default='info@mentoredgroup.com', max_length=254, verbose_name='Email для связи')),
                ('whatsapp_number', models.CharField(blank=True, help_text='В международном формате без плюса и пробелов, например 51940304595', max_length=20, verbose_name='WhatsApp')),
                ('instagram_url', models.URLField(blank=True, verbose_name='Instagram')),
                ('facebook_url', models.URLField(blank=True, verbose_name='Facebook')),
                ('youtube_url', models.URLField(blank=True, verbose_name='YouTube')),
                ('linkedin_url', models.URLField(blank=True, verbose_name='LinkedIn')),
            ],
            options={
                'verbose_name': 'Настройки сайта',
                'verbose_name_plural': 'Настройки сайта',
            },
        ),
        migrations.RunPython(seed_site_settings, migrations.RunPython.noop),
    ]
